import '../style/global.css'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
export const revalidate=10;

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className="global">
      <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
